import type { Collection, Rarity, Skin } from "./types";

export const COLLECTIONS: Collection[] = [
  { id: "phoenix", name: "The Phoenix Collection" },
  { id: "safehouse", name: "The Safehouse Collection" },
  { id: "chop-shop", name: "The Chop Shop Collection" },
  { id: "dust", name: "The Dust Collection" },
  { id: "cache", name: "The Cache Collection" },
  { id: "cobblestone", name: "The Cobblestone Collection" },
];

// Representative CS2 skins with real float ranges and collection membership
// Float ranges sourced from CS2 game data
export const SKINS: Skin[] = [
  // ─── The Phoenix Collection ───────────────────────────────
  // Consumer Grade
  {
    id: "mac10-palm",
    name: "MAC-10 | Palm",
    weaponName: "MAC-10",
    skinName: "Palm",
    collectionId: "phoenix",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "p2000-military-marine",
    name: "P2000 | Military Marine",
    weaponName: "P2000",
    skinName: "Military Marine",
    collectionId: "phoenix",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "usp-s-forest-leaves",
    name: "USP-S | Forest Leaves",
    weaponName: "USP-S",
    skinName: "Forest Leaves",
    collectionId: "phoenix",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Industrial Grade
  {
    id: "famas-valence",
    name: "FAMAS | Valence",
    weaponName: "FAMAS",
    skinName: "Valence",
    collectionId: "phoenix",
    rarity: "industrial_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "p90-storm",
    name: "P90 | Storm",
    weaponName: "P90",
    skinName: "Storm",
    collectionId: "phoenix",
    rarity: "industrial_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Mil-Spec
  {
    id: "p2000-ivory",
    name: "P2000 | Ivory",
    weaponName: "P2000",
    skinName: "Ivory",
    collectionId: "phoenix",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "mp7-urban-hazard",
    name: "MP7 | Urban Hazard",
    weaponName: "MP7",
    skinName: "Urban Hazard",
    collectionId: "phoenix",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "glock-18-dragon-tattoo",
    name: "Glock-18 | Dragon Tattoo",
    weaponName: "Glock-18",
    skinName: "Dragon Tattoo",
    collectionId: "phoenix",
    rarity: "mil_spec",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Restricted
  {
    id: "five-seven-fowl-play",
    name: "Five-SeveN | Fowl Play",
    weaponName: "Five-SeveN",
    skinName: "Fowl Play",
    collectionId: "phoenix",
    rarity: "restricted",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "usp-s-para-green",
    name: "USP-S | Para Green",
    weaponName: "USP-S",
    skinName: "Para Green",
    collectionId: "phoenix",
    rarity: "restricted",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Classified
  {
    id: "m4a4-asiimov",
    name: "M4A4 | Asiimov",
    weaponName: "M4A4",
    skinName: "Asiimov",
    collectionId: "phoenix",
    rarity: "classified",
    minFloat: 0.18,
    maxFloat: 1.0,
    stattrak: false,
  },
  // Covert
  {
    id: "ak47-vulcan",
    name: "AK-47 | Vulcan",
    weaponName: "AK-47",
    skinName: "Vulcan",
    collectionId: "phoenix",
    rarity: "covert",
    minFloat: 0.0,
    maxFloat: 1.0,
    stattrak: false,
  },

  // ─── The Safehouse Collection ─────────────────────────────
  // Consumer Grade
  {
    id: "mp5-sd-lab-rats",
    name: "MP5-SD | Lab Rats",
    weaponName: "MP5-SD",
    skinName: "Lab Rats",
    collectionId: "safehouse",
    rarity: "consumer_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  {
    id: "nova-caged-steel",
    name: "Nova | Caged Steel",
    weaponName: "Nova",
    skinName: "Caged Steel",
    collectionId: "safehouse",
    rarity: "consumer_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  // Industrial Grade
  {
    id: "mac10-tec9-hurricane",
    name: "Tec-9 | Avalanche",
    weaponName: "Tec-9",
    skinName: "Avalanche",
    collectionId: "safehouse",
    rarity: "industrial_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  {
    id: "p250-splash",
    name: "P250 | Splash",
    weaponName: "P250",
    skinName: "Splash",
    collectionId: "safehouse",
    rarity: "industrial_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  // Mil-Spec
  {
    id: "mp9-slide",
    name: "MP9 | Slide",
    weaponName: "MP9",
    skinName: "Slide",
    collectionId: "safehouse",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  {
    id: "sawed-off-forest-ddpat",
    name: "Sawed-Off | Forest DDPAT",
    weaponName: "Sawed-Off",
    skinName: "Forest DDPAT",
    collectionId: "safehouse",
    rarity: "mil_spec",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Restricted
  {
    id: "m4a1-s-bright-water",
    name: "M4A1-S | Bright Water",
    weaponName: "M4A1-S",
    skinName: "Bright Water",
    collectionId: "safehouse",
    rarity: "restricted",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "mac10-graven",
    name: "MAC-10 | Graven",
    weaponName: "MAC-10",
    skinName: "Graven",
    collectionId: "safehouse",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  // Classified
  {
    id: "deagle-hypnotic",
    name: "Desert Eagle | Hypnotic",
    weaponName: "Desert Eagle",
    skinName: "Hypnotic",
    collectionId: "safehouse",
    rarity: "classified",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Covert
  {
    id: "awp-asiimov",
    name: "AWP | Asiimov",
    weaponName: "AWP",
    skinName: "Asiimov",
    collectionId: "safehouse",
    rarity: "covert",
    minFloat: 0.18,
    maxFloat: 1.0,
    stattrak: false,
  },

  // ─── The Chop Shop Collection ─────────────────────────────
  // Consumer Grade
  {
    id: "p250-sand-dune",
    name: "P250 | Sand Dune",
    weaponName: "P250",
    skinName: "Sand Dune",
    collectionId: "chop-shop",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "nova-army-mesh",
    name: "Nova | Army Mesh",
    weaponName: "Nova",
    skinName: "Army Mesh",
    collectionId: "chop-shop",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Industrial Grade
  {
    id: "mp9-sand-scale",
    name: "MP9 | Sand Scale",
    weaponName: "MP9",
    skinName: "Sand Scale",
    collectionId: "chop-shop",
    rarity: "industrial_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  {
    id: "ssg08-sand-mesh",
    name: "SSG 08 | Sand Mesh",
    weaponName: "SSG 08",
    skinName: "Sand Mesh",
    collectionId: "chop-shop",
    rarity: "industrial_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  // Mil-Spec
  {
    id: "p90-sand-spray",
    name: "P90 | Sand Spray",
    weaponName: "P90",
    skinName: "Sand Spray",
    collectionId: "chop-shop",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "usp-s-cyrex",
    name: "USP-S | Cyrex",
    weaponName: "USP-S",
    skinName: "Cyrex",
    collectionId: "chop-shop",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  // Restricted
  {
    id: "ak47-cartel",
    name: "AK-47 | Cartel",
    weaponName: "AK-47",
    skinName: "Cartel",
    collectionId: "chop-shop",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "m4a4-spider-lily",
    name: "M4A4 | Spider Lily",
    weaponName: "M4A4",
    skinName: "Spider Lily",
    collectionId: "chop-shop",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  // Classified
  {
    id: "mp9-hypnotic",
    name: "MP9 | Hypnotic",
    weaponName: "MP9",
    skinName: "Hypnotic",
    collectionId: "chop-shop",
    rarity: "classified",
    minFloat: 0.0,
    maxFloat: 0.6,
    stattrak: false,
  },
  // Covert
  {
    id: "m4a1-s-cyrex",
    name: "M4A1-S | Cyrex",
    weaponName: "M4A1-S",
    skinName: "Cyrex",
    collectionId: "chop-shop",
    rarity: "covert",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },

  // ─── The Dust Collection ──────────────────────────────────
  // Consumer Grade
  {
    id: "ak47-sand-dune",
    name: "AK-47 | Sand Dune",
    weaponName: "AK-47",
    skinName: "Sand Dune",
    collectionId: "dust",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "m4a1-s-sand-storm",
    name: "M4A1-S | Sand Storm",
    weaponName: "M4A1-S",
    skinName: "Sand Storm",
    collectionId: "dust",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Industrial Grade
  {
    id: "deagle-night",
    name: "Desert Eagle | Night",
    weaponName: "Desert Eagle",
    skinName: "Night",
    collectionId: "dust",
    rarity: "industrial_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "galil-ar-gray",
    name: "Galil AR | Grey",
    weaponName: "Galil AR",
    skinName: "Grey",
    collectionId: "dust",
    rarity: "industrial_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Mil-Spec
  {
    id: "p250-undertow",
    name: "P250 | Undertow",
    weaponName: "P250",
    skinName: "Undertow",
    collectionId: "dust",
    rarity: "mil_spec",
    minFloat: 0.01,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "awp-safari-mesh",
    name: "AWP | Safari Mesh",
    weaponName: "AWP",
    skinName: "Safari Mesh",
    collectionId: "dust",
    rarity: "mil_spec",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Restricted
  {
    id: "ak47-redline",
    name: "AK-47 | Redline",
    weaponName: "AK-47",
    skinName: "Redline",
    collectionId: "dust",
    rarity: "restricted",
    minFloat: 0.1,
    maxFloat: 0.7,
    stattrak: false,
  },
  {
    id: "m4a1-s-bright-water-dust",
    name: "M4A1-S | Bright Water",
    weaponName: "M4A1-S",
    skinName: "Bright Water",
    collectionId: "dust",
    rarity: "restricted",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Classified
  {
    id: "deagle-desert-eagle-hypnotic",
    name: "Desert Eagle | Hypnotic",
    weaponName: "Desert Eagle",
    skinName: "Hypnotic",
    collectionId: "dust",
    rarity: "classified",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Covert
  {
    id: "awp-asiimov-dust",
    name: "AWP | Asiimov",
    weaponName: "AWP",
    skinName: "Asiimov",
    collectionId: "dust",
    rarity: "covert",
    minFloat: 0.18,
    maxFloat: 1.0,
    stattrak: false,
  },

  // ─── The Cache Collection ─────────────────────────────────
  // Consumer Grade
  {
    id: "mp5sd-phosphor",
    name: "MP5-SD | Phosphor",
    weaponName: "MP5-SD",
    skinName: "Phosphor",
    collectionId: "cache",
    rarity: "consumer_grade",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  {
    id: "p2000-amber-fade",
    name: "P2000 | Amber Fade",
    weaponName: "P2000",
    skinName: "Amber Fade",
    collectionId: "cache",
    rarity: "consumer_grade",
    minFloat: 0.0,
    maxFloat: 0.08,
    stattrak: false,
  },
  // Industrial Grade
  {
    id: "galil-ar-rocket-pop",
    name: "Galil AR | Rocket Pop",
    weaponName: "Galil AR",
    skinName: "Rocket Pop",
    collectionId: "cache",
    rarity: "industrial_grade",
    minFloat: 0.0,
    maxFloat: 0.6,
    stattrak: false,
  },
  {
    id: "mp9-hypnotic-cache",
    name: "MP9 | Hypnotic",
    weaponName: "MP9",
    skinName: "Hypnotic",
    collectionId: "cache",
    rarity: "industrial_grade",
    minFloat: 0.0,
    maxFloat: 0.6,
    stattrak: false,
  },
  // Mil-Spec
  {
    id: "scar20-grotto",
    name: "SCAR-20 | Grotto",
    weaponName: "SCAR-20",
    skinName: "Grotto",
    collectionId: "cache",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "mp7-skulls",
    name: "MP7 | Skulls",
    weaponName: "MP7",
    skinName: "Skulls",
    collectionId: "cache",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  // Restricted
  {
    id: "sg553-aerial",
    name: "SG 553 | Aerial",
    weaponName: "SG 553",
    skinName: "Aerial",
    collectionId: "cache",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.6,
    stattrak: false,
  },
  {
    id: "m4a4-radiation-hazard",
    name: "M4A4 | Radiation Hazard",
    weaponName: "M4A4",
    skinName: "Radiation Hazard",
    collectionId: "cache",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  // Classified
  {
    id: "ak47-wasteland-rebel",
    name: "AK-47 | Wasteland Rebel",
    weaponName: "AK-47",
    skinName: "Wasteland Rebel",
    collectionId: "cache",
    rarity: "classified",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
  // Covert
  {
    id: "m4a4-howl",
    name: "M4A4 | Howl",
    weaponName: "M4A4",
    skinName: "Howl",
    collectionId: "cache",
    rarity: "covert",
    minFloat: 0.0,
    maxFloat: 0.4,
    stattrak: false,
  },

  // ─── The Cobblestone Collection ───────────────────────────
  // Consumer Grade
  {
    id: "famas-afterimage",
    name: "FAMAS | Afterimage",
    weaponName: "FAMAS",
    skinName: "Afterimage",
    collectionId: "cobblestone",
    rarity: "consumer_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "mp5sd-desert-strike",
    name: "MP5-SD | Desert Strike",
    weaponName: "MP5-SD",
    skinName: "Desert Strike",
    collectionId: "cobblestone",
    rarity: "consumer_grade",
    minFloat: 0.0,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Industrial Grade
  {
    id: "sg553-waves-perforated",
    name: "SG 553 | Waves Perforated",
    weaponName: "SG 553",
    skinName: "Waves Perforated",
    collectionId: "cobblestone",
    rarity: "industrial_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  {
    id: "ump45-contracted",
    name: "UMP-45 | Contracted",
    weaponName: "UMP-45",
    skinName: "Contracted",
    collectionId: "cobblestone",
    rarity: "industrial_grade",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Mil-Spec
  {
    id: "p250-check-pattern",
    name: "P250 | Check Pattern",
    weaponName: "P250",
    skinName: "Check Pattern",
    collectionId: "cobblestone",
    rarity: "mil_spec",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "xm1014-jungle",
    name: "XM1014 | Jungle",
    weaponName: "XM1014",
    skinName: "Jungle",
    collectionId: "cobblestone",
    rarity: "mil_spec",
    minFloat: 0.06,
    maxFloat: 0.8,
    stattrak: false,
  },
  // Restricted
  {
    id: "ssg08-cobalt-core",
    name: "SSG 08 | Cobalt Core",
    weaponName: "SSG 08",
    skinName: "Cobalt Core",
    collectionId: "cobblestone",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  {
    id: "mp9-ruby-poison-dart",
    name: "MP9 | Ruby Poison Dart",
    weaponName: "MP9",
    skinName: "Ruby Poison Dart",
    collectionId: "cobblestone",
    rarity: "restricted",
    minFloat: 0.0,
    maxFloat: 0.5,
    stattrak: false,
  },
  // Classified
  {
    id: "m4a4-dragon-king",
    name: "M4A4 | Dragon King",
    weaponName: "M4A4",
    skinName: "Dragon King",
    collectionId: "cobblestone",
    rarity: "classified",
    minFloat: 0.0,
    maxFloat: 0.4,
    stattrak: false,
  },
  // Covert
  {
    id: "awp-wildfire",
    name: "AWP | Wildfire",
    weaponName: "AWP",
    skinName: "Wildfire",
    collectionId: "cobblestone",
    rarity: "covert",
    minFloat: 0.0,
    maxFloat: 0.7,
    stattrak: false,
  },
];

export function getSkinById(id: string): Skin | undefined {
  return SKINS.find((s) => s.id === id);
}

export function getCollectionById(id: string): Collection | undefined {
  return COLLECTIONS.find((c) => c.id === id);
}

export function getSkinsByRarity(rarity: Rarity): Skin[] {
  return SKINS.filter((s) => s.rarity === rarity);
}

export function getSkinsByCollection(collectionId: string): Skin[] {
  return SKINS.filter((s) => s.collectionId === collectionId);
}

export function getSkinsByCollectionAndRarity(
  collectionId: string,
  rarity: Rarity,
): Skin[] {
  return SKINS.filter(
    (s) => s.collectionId === collectionId && s.rarity === rarity,
  );
}
